### PR TITLE
Jbranch

### PR DESCRIPTION
**Pull request by JesseSoldat**
no user 
----------------------------------------------------------------
logged in data is loaded from json file
can NOT access favorite buttons from list/details

logged in user
----------------------------------------------------------------
user has not picked any favorites data is loaded from json file
user has at least one favorite picked data is loaded from firebase
user can access favorite buttons from list/details

Both
----------------------------------------------------------------
spinner included

### CODE REVIEW

**Comment by siamkreative** [comment]
Thanks for your contribution! I will review it asap

**Comment by siamkreative** [comment]
That's a really great improvement. However, I have a few comments:

1. I would like to keep the "Save favorite" button for logged-out users. It's one of the main features of the app and if users can't see it, they will probably never be aware of it. For logged-out users, the `uiSidebarRight` should slide in so that they understand they have to log in first.
2. (Might not directly be related to this PR), but the favorites do not show up in `uiSidebarRight` when the user is logged-in. This could be fixed in another development as I would like improve the UI and how favorites are displayed in the "user" sidebar.

If you "fix" the first one I will definitely merge this great PR :)

**Comment by JesseSoldat** [comment]
I added the fav buttons that take a user to the login page.  

I see that the favorite page only updates on refresh

**Comment by JesseSoldat** [comment]
What I see as a problem is that the sidebar right does not connect to a controller.  For the other pages every time we navigate to a page the controller updates the data. However the side bar is left with stale data from the first page load.  I am guessing it gets it from here (ng-init="parentIndex = $index")

**Pull request merged**
